language: node_js

node_js:
  - "8"
  
sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ca-central-1"  
  app: "instant-chat-server"
  env: "instant-chat-server"
  bucket_name: "elasticbeanstalk-ca-central-1-882371129764"
  on:
    branch: master



before_script:
  - docker build -t chat-server .
  - docker images
  - docker run -p 4000:8080 -e SECRET=$SECRET -e DBCONFIG=$DBCONFIG -d chat-server
  - sleep 15
  - docker ps